version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        # Update 'VARIANT' to pick an LTS version of Node.js: 16, 14.
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: 18-bullseye

    volumes:
      - ..:/workspace:cached
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    env_file:
      # Ensure that the variables in .env match the same variables in devcontainer.json
      - .env
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db

    # Uncomment the next line to use a non-root user for all processes.
    # user: node

    # ports:
    #   - 9099:9099 # Auth
    #   - 4000:4000 # Emulator Suite UI
    #   - 5001:5001 # Cloud Functions
    #   - 8080:8080 # Cloud Firestore
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./create-db-user.sql:/docker-entrypoint-initdb.d/create-db-user.sql
    env_file:
        # Ensure that the variables in .env match the same variables in devcontainer.json
        - .env

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  adminer:
    image: dpage/pgadmin4
    restart: always
    # network_mode: service:db
    env_file:
        # Ensure that the variables in .env match the same variables in devcontainer.json
        - .env
    ports:
      - 8080:80
      